<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2025/10/26 18:30:31
sfConfig::add(array(
  'mod_informationobject_enabled' => true,
  'mod_informationobject_view_class' => 'sfPHP',
));
