<?php
// auto-generated by sfCacheConfigHandler
// date: 2025/10/28 06:33:22
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

