<?php
// auto-generated by sfCacheConfigHandler
// date: 2025/10/26 18:30:31
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

